/*
 * This file is generated by jOOQ.
 */
package com.thhkpr.databases.tables.records;


import com.thhkpr.databases.tables.Storage;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StorageRecord extends UpdatableRecordImpl<StorageRecord> implements Record7<Integer, String, String, String, Timestamp, Timestamp, String> {

    private static final long serialVersionUID = 294830904;

    /**
     * Setter for <code>thhkpr.storage.storage_id</code>.
     */
    public void setStorageId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>thhkpr.storage.storage_id</code>.
     */
    public Integer getStorageId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>thhkpr.storage.storage_name</code>.
     */
    public void setStorageName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>thhkpr.storage.storage_name</code>.
     */
    public String getStorageName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>thhkpr.storage.storage_describe</code>.
     */
    public void setStorageDescribe(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>thhkpr.storage.storage_describe</code>.
     */
    public String getStorageDescribe() {
        return (String) get(2);
    }

    /**
     * Setter for <code>thhkpr.storage.storage_place</code>.
     */
    public void setStoragePlace(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>thhkpr.storage.storage_place</code>.
     */
    public String getStoragePlace() {
        return (String) get(3);
    }

    /**
     * Setter for <code>thhkpr.storage.sys_date_create</code>.
     */
    public void setSysDateCreate(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>thhkpr.storage.sys_date_create</code>.
     */
    public Timestamp getSysDateCreate() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>thhkpr.storage.sys_date_update</code>.
     */
    public void setSysDateUpdate(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>thhkpr.storage.sys_date_update</code>.
     */
    public Timestamp getSysDateUpdate() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>thhkpr.storage.sys_who_update_name</code>.
     */
    public void setSysWhoUpdateName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>thhkpr.storage.sys_who_update_name</code>.
     */
    public String getSysWhoUpdateName() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, String, Timestamp, Timestamp, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, String, Timestamp, Timestamp, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Storage.STORAGE.STORAGE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Storage.STORAGE.STORAGE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Storage.STORAGE.STORAGE_DESCRIBE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Storage.STORAGE.STORAGE_PLACE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Storage.STORAGE.SYS_DATE_CREATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Storage.STORAGE.SYS_DATE_UPDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Storage.STORAGE.SYS_WHO_UPDATE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getStorageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getStorageName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getStorageDescribe();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getStoragePlace();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getSysDateCreate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getSysDateUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getSysWhoUpdateName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getStorageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getStorageName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getStorageDescribe();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getStoragePlace();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getSysDateCreate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getSysDateUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getSysWhoUpdateName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StorageRecord value1(Integer value) {
        setStorageId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StorageRecord value2(String value) {
        setStorageName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StorageRecord value3(String value) {
        setStorageDescribe(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StorageRecord value4(String value) {
        setStoragePlace(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StorageRecord value5(Timestamp value) {
        setSysDateCreate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StorageRecord value6(Timestamp value) {
        setSysDateUpdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StorageRecord value7(String value) {
        setSysWhoUpdateName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StorageRecord values(Integer value1, String value2, String value3, String value4, Timestamp value5, Timestamp value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StorageRecord
     */
    public StorageRecord() {
        super(Storage.STORAGE);
    }

    /**
     * Create a detached, initialised StorageRecord
     */
    public StorageRecord(Integer storageId, String storageName, String storageDescribe, String storagePlace, Timestamp sysDateCreate, Timestamp sysDateUpdate, String sysWhoUpdateName) {
        super(Storage.STORAGE);

        set(0, storageId);
        set(1, storageName);
        set(2, storageDescribe);
        set(3, storagePlace);
        set(4, sysDateCreate);
        set(5, sysDateUpdate);
        set(6, sysWhoUpdateName);
    }
}
