/*
 * This file is generated by jOOQ.
 */
package com.thhkpr.databases.tables.records;


import com.thhkpr.databases.tables.Things;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ThingsRecord extends UpdatableRecordImpl<ThingsRecord> implements Record8<Integer, String, String, byte[], Timestamp, Timestamp, String, Integer> {

    private static final long serialVersionUID = 1794163591;

    /**
     * Setter for <code>thhkpr.things.thing_id</code>.
     */
    public void setThingId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>thhkpr.things.thing_id</code>.
     */
    public Integer getThingId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>thhkpr.things.thing_name</code>.
     */
    public void setThingName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>thhkpr.things.thing_name</code>.
     */
    public String getThingName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>thhkpr.things.thing_describe</code>.
     */
    public void setThingDescribe(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>thhkpr.things.thing_describe</code>.
     */
    public String getThingDescribe() {
        return (String) get(2);
    }

    /**
     * Setter for <code>thhkpr.things.thing_voice</code>.
     */
    public void setThingVoice(byte... value) {
        set(3, value);
    }

    /**
     * Getter for <code>thhkpr.things.thing_voice</code>.
     */
    public byte[] getThingVoice() {
        return (byte[]) get(3);
    }

    /**
     * Setter for <code>thhkpr.things.sys_date_create</code>.
     */
    public void setSysDateCreate(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>thhkpr.things.sys_date_create</code>.
     */
    public Timestamp getSysDateCreate() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>thhkpr.things.sys_date_update</code>.
     */
    public void setSysDateUpdate(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>thhkpr.things.sys_date_update</code>.
     */
    public Timestamp getSysDateUpdate() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>thhkpr.things.sys_who_update_name</code>.
     */
    public void setSysWhoUpdateName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>thhkpr.things.sys_who_update_name</code>.
     */
    public String getSysWhoUpdateName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>thhkpr.things.storage_id</code>.
     */
    public void setStorageId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>thhkpr.things.storage_id</code>.
     */
    public Integer getStorageId() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, byte[], Timestamp, Timestamp, String, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, byte[], Timestamp, Timestamp, String, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Things.THINGS.THING_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Things.THINGS.THING_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Things.THINGS.THING_DESCRIBE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field4() {
        return Things.THINGS.THING_VOICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Things.THINGS.SYS_DATE_CREATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Things.THINGS.SYS_DATE_UPDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Things.THINGS.SYS_WHO_UPDATE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Things.THINGS.STORAGE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getThingId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getThingName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getThingDescribe();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component4() {
        return getThingVoice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getSysDateCreate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getSysDateUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getSysWhoUpdateName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getStorageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getThingId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getThingName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getThingDescribe();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value4() {
        return getThingVoice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getSysDateCreate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getSysDateUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getSysWhoUpdateName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getStorageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ThingsRecord value1(Integer value) {
        setThingId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ThingsRecord value2(String value) {
        setThingName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ThingsRecord value3(String value) {
        setThingDescribe(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ThingsRecord value4(byte... value) {
        setThingVoice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ThingsRecord value5(Timestamp value) {
        setSysDateCreate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ThingsRecord value6(Timestamp value) {
        setSysDateUpdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ThingsRecord value7(String value) {
        setSysWhoUpdateName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ThingsRecord value8(Integer value) {
        setStorageId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ThingsRecord values(Integer value1, String value2, String value3, byte[] value4, Timestamp value5, Timestamp value6, String value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ThingsRecord
     */
    public ThingsRecord() {
        super(Things.THINGS);
    }

    /**
     * Create a detached, initialised ThingsRecord
     */
    public ThingsRecord(Integer thingId, String thingName, String thingDescribe, byte[] thingVoice, Timestamp sysDateCreate, Timestamp sysDateUpdate, String sysWhoUpdateName, Integer storageId) {
        super(Things.THINGS);

        set(0, thingId);
        set(1, thingName);
        set(2, thingDescribe);
        set(3, thingVoice);
        set(4, sysDateCreate);
        set(5, sysDateUpdate);
        set(6, sysWhoUpdateName);
        set(7, storageId);
    }
}
