/*
 * This file is generated by jOOQ.
 */
package com.thhkpr.databases.tables.daos;


import com.thhkpr.databases.tables.Storage;
import com.thhkpr.databases.tables.records.StorageRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StorageDao extends DAOImpl<StorageRecord, com.thhkpr.databases.tables.pojos.Storage, Integer> {

    /**
     * Create a new StorageDao without any configuration
     */
    public StorageDao() {
        super(Storage.STORAGE, com.thhkpr.databases.tables.pojos.Storage.class);
    }

    /**
     * Create a new StorageDao with an attached configuration
     */
    public StorageDao(Configuration configuration) {
        super(Storage.STORAGE, com.thhkpr.databases.tables.pojos.Storage.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.thhkpr.databases.tables.pojos.Storage object) {
        return object.getStorageId();
    }

    /**
     * Fetch records that have <code>storage_id IN (values)</code>
     */
    public List<com.thhkpr.databases.tables.pojos.Storage> fetchByStorageId(Integer... values) {
        return fetch(Storage.STORAGE.STORAGE_ID, values);
    }

    /**
     * Fetch a unique record that has <code>storage_id = value</code>
     */
    public com.thhkpr.databases.tables.pojos.Storage fetchOneByStorageId(Integer value) {
        return fetchOne(Storage.STORAGE.STORAGE_ID, value);
    }

    /**
     * Fetch records that have <code>storage_name IN (values)</code>
     */
    public List<com.thhkpr.databases.tables.pojos.Storage> fetchByStorageName(String... values) {
        return fetch(Storage.STORAGE.STORAGE_NAME, values);
    }

    /**
     * Fetch records that have <code>storage_describe IN (values)</code>
     */
    public List<com.thhkpr.databases.tables.pojos.Storage> fetchByStorageDescribe(String... values) {
        return fetch(Storage.STORAGE.STORAGE_DESCRIBE, values);
    }

    /**
     * Fetch records that have <code>storage_place IN (values)</code>
     */
    public List<com.thhkpr.databases.tables.pojos.Storage> fetchByStoragePlace(String... values) {
        return fetch(Storage.STORAGE.STORAGE_PLACE, values);
    }

    /**
     * Fetch records that have <code>sys_date_create IN (values)</code>
     */
    public List<com.thhkpr.databases.tables.pojos.Storage> fetchBySysDateCreate(Timestamp... values) {
        return fetch(Storage.STORAGE.SYS_DATE_CREATE, values);
    }

    /**
     * Fetch records that have <code>sys_date_update IN (values)</code>
     */
    public List<com.thhkpr.databases.tables.pojos.Storage> fetchBySysDateUpdate(Timestamp... values) {
        return fetch(Storage.STORAGE.SYS_DATE_UPDATE, values);
    }

    /**
     * Fetch records that have <code>sys_who_update_name IN (values)</code>
     */
    public List<com.thhkpr.databases.tables.pojos.Storage> fetchBySysWhoUpdateName(String... values) {
        return fetch(Storage.STORAGE.SYS_WHO_UPDATE_NAME, values);
    }
}
