/*
 * This file is generated by jOOQ.
 */
package com.thhkpr.databases.tables.daos;


import com.thhkpr.databases.tables.Things;
import com.thhkpr.databases.tables.records.ThingsRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ThingsDao extends DAOImpl<ThingsRecord, com.thhkpr.databases.tables.pojos.Things, Integer> {

    /**
     * Create a new ThingsDao without any configuration
     */
    public ThingsDao() {
        super(Things.THINGS, com.thhkpr.databases.tables.pojos.Things.class);
    }

    /**
     * Create a new ThingsDao with an attached configuration
     */
    public ThingsDao(Configuration configuration) {
        super(Things.THINGS, com.thhkpr.databases.tables.pojos.Things.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.thhkpr.databases.tables.pojos.Things object) {
        return object.getThingId();
    }

    /**
     * Fetch records that have <code>thing_id IN (values)</code>
     */
    public List<com.thhkpr.databases.tables.pojos.Things> fetchByThingId(Integer... values) {
        return fetch(Things.THINGS.THING_ID, values);
    }

    /**
     * Fetch a unique record that has <code>thing_id = value</code>
     */
    public com.thhkpr.databases.tables.pojos.Things fetchOneByThingId(Integer value) {
        return fetchOne(Things.THINGS.THING_ID, value);
    }

    /**
     * Fetch records that have <code>thing_name IN (values)</code>
     */
    public List<com.thhkpr.databases.tables.pojos.Things> fetchByThingName(String... values) {
        return fetch(Things.THINGS.THING_NAME, values);
    }

    /**
     * Fetch records that have <code>thing_describe IN (values)</code>
     */
    public List<com.thhkpr.databases.tables.pojos.Things> fetchByThingDescribe(String... values) {
        return fetch(Things.THINGS.THING_DESCRIBE, values);
    }

    /**
     * Fetch records that have <code>thing_voice IN (values)</code>
     */
    public List<com.thhkpr.databases.tables.pojos.Things> fetchByThingVoice(byte[]... values) {
        return fetch(Things.THINGS.THING_VOICE, values);
    }

    /**
     * Fetch records that have <code>sys_date_create IN (values)</code>
     */
    public List<com.thhkpr.databases.tables.pojos.Things> fetchBySysDateCreate(Timestamp... values) {
        return fetch(Things.THINGS.SYS_DATE_CREATE, values);
    }

    /**
     * Fetch records that have <code>sys_date_update IN (values)</code>
     */
    public List<com.thhkpr.databases.tables.pojos.Things> fetchBySysDateUpdate(Timestamp... values) {
        return fetch(Things.THINGS.SYS_DATE_UPDATE, values);
    }

    /**
     * Fetch records that have <code>sys_who_update_name IN (values)</code>
     */
    public List<com.thhkpr.databases.tables.pojos.Things> fetchBySysWhoUpdateName(String... values) {
        return fetch(Things.THINGS.SYS_WHO_UPDATE_NAME, values);
    }

    /**
     * Fetch records that have <code>storage_id IN (values)</code>
     */
    public List<com.thhkpr.databases.tables.pojos.Things> fetchByStorageId(Integer... values) {
        return fetch(Things.THINGS.STORAGE_ID, values);
    }
}
