/*
 * This file is generated by jOOQ.
 */
package com.thhkpr.databases.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Settings implements Serializable {

    private static final long serialVersionUID = 2010281764;

    private ULong  settingsId;
    private String settingsName;
    private String settingsValue;

    public Settings() {}

    public Settings(Settings value) {
        this.settingsId = value.settingsId;
        this.settingsName = value.settingsName;
        this.settingsValue = value.settingsValue;
    }

    public Settings(
        ULong  settingsId,
        String settingsName,
        String settingsValue
    ) {
        this.settingsId = settingsId;
        this.settingsName = settingsName;
        this.settingsValue = settingsValue;
    }

    public ULong getSettingsId() {
        return this.settingsId;
    }

    public void setSettingsId(ULong settingsId) {
        this.settingsId = settingsId;
    }

    public String getSettingsName() {
        return this.settingsName;
    }

    public void setSettingsName(String settingsName) {
        this.settingsName = settingsName;
    }

    public String getSettingsValue() {
        return this.settingsValue;
    }

    public void setSettingsValue(String settingsValue) {
        this.settingsValue = settingsValue;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Settings (");

        sb.append(settingsId);
        sb.append(", ").append(settingsName);
        sb.append(", ").append(settingsValue);

        sb.append(")");
        return sb.toString();
    }
}
