/*
 * This file is generated by jOOQ.
 */
package com.thhkpr.databases.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Storage implements Serializable {

    private static final long serialVersionUID = 247009704;

    private ULong     storageId;
    private String    storageName;
    private String    storageDescribe;
    private String    storagePlace;
    private Timestamp sysDateCreate;
    private Timestamp sysDateUpdate;
    private String    sysWhoUpdateName;

    public Storage() {}

    public Storage(Storage value) {
        this.storageId = value.storageId;
        this.storageName = value.storageName;
        this.storageDescribe = value.storageDescribe;
        this.storagePlace = value.storagePlace;
        this.sysDateCreate = value.sysDateCreate;
        this.sysDateUpdate = value.sysDateUpdate;
        this.sysWhoUpdateName = value.sysWhoUpdateName;
    }

    public Storage(
        ULong     storageId,
        String    storageName,
        String    storageDescribe,
        String    storagePlace,
        Timestamp sysDateCreate,
        Timestamp sysDateUpdate,
        String    sysWhoUpdateName
    ) {
        this.storageId = storageId;
        this.storageName = storageName;
        this.storageDescribe = storageDescribe;
        this.storagePlace = storagePlace;
        this.sysDateCreate = sysDateCreate;
        this.sysDateUpdate = sysDateUpdate;
        this.sysWhoUpdateName = sysWhoUpdateName;
    }

    public ULong getStorageId() {
        return this.storageId;
    }

    public void setStorageId(ULong storageId) {
        this.storageId = storageId;
    }

    public String getStorageName() {
        return this.storageName;
    }

    public void setStorageName(String storageName) {
        this.storageName = storageName;
    }

    public String getStorageDescribe() {
        return this.storageDescribe;
    }

    public void setStorageDescribe(String storageDescribe) {
        this.storageDescribe = storageDescribe;
    }

    public String getStoragePlace() {
        return this.storagePlace;
    }

    public void setStoragePlace(String storagePlace) {
        this.storagePlace = storagePlace;
    }

    public Timestamp getSysDateCreate() {
        return this.sysDateCreate;
    }

    public void setSysDateCreate(Timestamp sysDateCreate) {
        this.sysDateCreate = sysDateCreate;
    }

    public Timestamp getSysDateUpdate() {
        return this.sysDateUpdate;
    }

    public void setSysDateUpdate(Timestamp sysDateUpdate) {
        this.sysDateUpdate = sysDateUpdate;
    }

    public String getSysWhoUpdateName() {
        return this.sysWhoUpdateName;
    }

    public void setSysWhoUpdateName(String sysWhoUpdateName) {
        this.sysWhoUpdateName = sysWhoUpdateName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Storage (");

        sb.append(storageId);
        sb.append(", ").append(storageName);
        sb.append(", ").append(storageDescribe);
        sb.append(", ").append(storagePlace);
        sb.append(", ").append(sysDateCreate);
        sb.append(", ").append(sysDateUpdate);
        sb.append(", ").append(sysWhoUpdateName);

        sb.append(")");
        return sb.toString();
    }
}
