/*
 * This file is generated by jOOQ.
 */
package com.thhkpr.databases.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Things implements Serializable {

    private static final long serialVersionUID = 426372912;

    private ULong     thingId;
    private String    thingName;
    private String    thingDescribe;
    private byte[]    thingVoice;
    private Timestamp sysDateCreate;
    private Timestamp sysDateUpdate;
    private String    sysWhoUpdateName;

    public Things() {}

    public Things(Things value) {
        this.thingId = value.thingId;
        this.thingName = value.thingName;
        this.thingDescribe = value.thingDescribe;
        this.thingVoice = value.thingVoice;
        this.sysDateCreate = value.sysDateCreate;
        this.sysDateUpdate = value.sysDateUpdate;
        this.sysWhoUpdateName = value.sysWhoUpdateName;
    }

    public Things(
        ULong     thingId,
        String    thingName,
        String    thingDescribe,
        byte[]    thingVoice,
        Timestamp sysDateCreate,
        Timestamp sysDateUpdate,
        String    sysWhoUpdateName
    ) {
        this.thingId = thingId;
        this.thingName = thingName;
        this.thingDescribe = thingDescribe;
        this.thingVoice = thingVoice;
        this.sysDateCreate = sysDateCreate;
        this.sysDateUpdate = sysDateUpdate;
        this.sysWhoUpdateName = sysWhoUpdateName;
    }

    public ULong getThingId() {
        return this.thingId;
    }

    public void setThingId(ULong thingId) {
        this.thingId = thingId;
    }

    public String getThingName() {
        return this.thingName;
    }

    public void setThingName(String thingName) {
        this.thingName = thingName;
    }

    public String getThingDescribe() {
        return this.thingDescribe;
    }

    public void setThingDescribe(String thingDescribe) {
        this.thingDescribe = thingDescribe;
    }

    public byte[] getThingVoice() {
        return this.thingVoice;
    }

    public void setThingVoice(byte... thingVoice) {
        this.thingVoice = thingVoice;
    }

    public Timestamp getSysDateCreate() {
        return this.sysDateCreate;
    }

    public void setSysDateCreate(Timestamp sysDateCreate) {
        this.sysDateCreate = sysDateCreate;
    }

    public Timestamp getSysDateUpdate() {
        return this.sysDateUpdate;
    }

    public void setSysDateUpdate(Timestamp sysDateUpdate) {
        this.sysDateUpdate = sysDateUpdate;
    }

    public String getSysWhoUpdateName() {
        return this.sysWhoUpdateName;
    }

    public void setSysWhoUpdateName(String sysWhoUpdateName) {
        this.sysWhoUpdateName = sysWhoUpdateName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Things (");

        sb.append(thingId);
        sb.append(", ").append(thingName);
        sb.append(", ").append(thingDescribe);
        sb.append(", ").append("[binary...]");
        sb.append(", ").append(sysDateCreate);
        sb.append(", ").append(sysDateUpdate);
        sb.append(", ").append(sysWhoUpdateName);

        sb.append(")");
        return sb.toString();
    }
}
