/*
 * This file is generated by jOOQ.
 */
package com.thhkpr.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "settings", schema = "thhkpr", indexes = {
    @Index(name = "PRIMARY", unique = true, columnList = "settings_id ASC"),
    @Index(name = "settings_id", unique = true, columnList = "settings_id ASC"),
    @Index(name = "settings_settings_id_index", columnList = "settings_id ASC"),
    @Index(name = "settings_settings_name_index", columnList = "settings_name ASC")
})
public class Settings implements Serializable {

    private static final long serialVersionUID = -846196220;

    private ULong  settingsId;
    private String settingsName;
    private String settingsValue;

    public Settings() {}

    public Settings(Settings value) {
        this.settingsId = value.settingsId;
        this.settingsName = value.settingsName;
        this.settingsValue = value.settingsValue;
    }

    public Settings(
        ULong  settingsId,
        String settingsName,
        String settingsValue
    ) {
        this.settingsId = settingsId;
        this.settingsName = settingsName;
        this.settingsValue = settingsValue;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "settings_id", unique = true, nullable = false, precision = 20)
    public ULong getSettingsId() {
        return this.settingsId;
    }

    public void setSettingsId(ULong settingsId) {
        this.settingsId = settingsId;
    }

    @Column(name = "settings_name", nullable = false, length = 255)
    @NotNull
    @Size(max = 255)
    public String getSettingsName() {
        return this.settingsName;
    }

    public void setSettingsName(String settingsName) {
        this.settingsName = settingsName;
    }

    @Column(name = "settings_value", length = 500)
    @Size(max = 500)
    public String getSettingsValue() {
        return this.settingsValue;
    }

    public void setSettingsValue(String settingsValue) {
        this.settingsValue = settingsValue;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Settings (");

        sb.append(settingsId);
        sb.append(", ").append(settingsName);
        sb.append(", ").append(settingsValue);

        sb.append(")");
        return sb.toString();
    }
}
