/*
 * This file is generated by jOOQ.
 */
package com.thhkpr.db.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "things", schema = "thhkpr", indexes = {
    @Index(name = "PRIMARY", unique = true, columnList = "thing_id ASC"),
    @Index(name = "things_thing_id_index", columnList = "thing_id ASC"),
    @Index(name = "things_thing_name_index", columnList = "thing_name ASC"),
    @Index(name = "thing_id", unique = true, columnList = "thing_id ASC")
})
public class Things implements Serializable {

    private static final long serialVersionUID = 1294640782;

    private ULong     thingId;
    private String    thingName;
    private String    thingDescribe;
    private byte[]    thnigVoice;
    private Timestamp sysDateCreate;
    private Timestamp sysDateUpdate;
    private String    sysWhoUpdateName;

    public Things() {}

    public Things(Things value) {
        this.thingId = value.thingId;
        this.thingName = value.thingName;
        this.thingDescribe = value.thingDescribe;
        this.thnigVoice = value.thnigVoice;
        this.sysDateCreate = value.sysDateCreate;
        this.sysDateUpdate = value.sysDateUpdate;
        this.sysWhoUpdateName = value.sysWhoUpdateName;
    }

    public Things(
        ULong     thingId,
        String    thingName,
        String    thingDescribe,
        byte[]    thnigVoice,
        Timestamp sysDateCreate,
        Timestamp sysDateUpdate,
        String    sysWhoUpdateName
    ) {
        this.thingId = thingId;
        this.thingName = thingName;
        this.thingDescribe = thingDescribe;
        this.thnigVoice = thnigVoice;
        this.sysDateCreate = sysDateCreate;
        this.sysDateUpdate = sysDateUpdate;
        this.sysWhoUpdateName = sysWhoUpdateName;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "thing_id", unique = true, nullable = false, precision = 20)
    public ULong getThingId() {
        return this.thingId;
    }

    public void setThingId(ULong thingId) {
        this.thingId = thingId;
    }

    @Column(name = "thing_name", nullable = false, length = 4000)
    @NotNull
    @Size(max = 4000)
    public String getThingName() {
        return this.thingName;
    }

    public void setThingName(String thingName) {
        this.thingName = thingName;
    }

    @Column(name = "thing_describe", length = 4000)
    @Size(max = 4000)
    public String getThingDescribe() {
        return this.thingDescribe;
    }

    public void setThingDescribe(String thingDescribe) {
        this.thingDescribe = thingDescribe;
    }

    @Column(name = "thnig_voice", length = 65535)
    @Size(max = 65535)
    public byte[] getThnigVoice() {
        return this.thnigVoice;
    }

    public void setThnigVoice(byte... thnigVoice) {
        this.thnigVoice = thnigVoice;
    }

    @Column(name = "sys_date_create", nullable = false)
    public Timestamp getSysDateCreate() {
        return this.sysDateCreate;
    }

    public void setSysDateCreate(Timestamp sysDateCreate) {
        this.sysDateCreate = sysDateCreate;
    }

    @Column(name = "sys_date_update", nullable = false)
    public Timestamp getSysDateUpdate() {
        return this.sysDateUpdate;
    }

    public void setSysDateUpdate(Timestamp sysDateUpdate) {
        this.sysDateUpdate = sysDateUpdate;
    }

    @Column(name = "sys_who_update_name", length = 500)
    @Size(max = 500)
    public String getSysWhoUpdateName() {
        return this.sysWhoUpdateName;
    }

    public void setSysWhoUpdateName(String sysWhoUpdateName) {
        this.sysWhoUpdateName = sysWhoUpdateName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Things (");

        sb.append(thingId);
        sb.append(", ").append(thingName);
        sb.append(", ").append(thingDescribe);
        sb.append(", ").append("[binary...]");
        sb.append(", ").append(sysDateCreate);
        sb.append(", ").append(sysDateUpdate);
        sb.append(", ").append(sysWhoUpdateName);

        sb.append(")");
        return sb.toString();
    }
}
