/*
 * This file is generated by jOOQ.
 */
package com.thhkpr.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "users", schema = "thhkpr", indexes = {
    @Index(name = "PRIMARY", unique = true, columnList = "user_id ASC"),
    @Index(name = "users_user_id_index", columnList = "user_id ASC"),
    @Index(name = "users_user_name_user_login_index", columnList = "user_name ASC, user_login ASC"),
    @Index(name = "user_id", unique = true, columnList = "user_id ASC")
})
public class Users implements Serializable {

    private static final long serialVersionUID = 402265764;

    private ULong   userId;
    private String  userName;
    private String  userLogin;
    private String  userPassword;
    private Integer userActive;

    public Users() {}

    public Users(Users value) {
        this.userId = value.userId;
        this.userName = value.userName;
        this.userLogin = value.userLogin;
        this.userPassword = value.userPassword;
        this.userActive = value.userActive;
    }

    public Users(
        ULong   userId,
        String  userName,
        String  userLogin,
        String  userPassword,
        Integer userActive
    ) {
        this.userId = userId;
        this.userName = userName;
        this.userLogin = userLogin;
        this.userPassword = userPassword;
        this.userActive = userActive;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "user_id", unique = true, nullable = false, precision = 20)
    public ULong getUserId() {
        return this.userId;
    }

    public void setUserId(ULong userId) {
        this.userId = userId;
    }

    @Column(name = "user_name", nullable = false, length = 500)
    @NotNull
    @Size(max = 500)
    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    @Column(name = "user_login", nullable = false, length = 80)
    @NotNull
    @Size(max = 80)
    public String getUserLogin() {
        return this.userLogin;
    }

    public void setUserLogin(String userLogin) {
        this.userLogin = userLogin;
    }

    @Column(name = "user_password", length = 80)
    @Size(max = 80)
    public String getUserPassword() {
        return this.userPassword;
    }

    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    @Column(name = "user_active", precision = 10)
    public Integer getUserActive() {
        return this.userActive;
    }

    public void setUserActive(Integer userActive) {
        this.userActive = userActive;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(userId);
        sb.append(", ").append(userName);
        sb.append(", ").append(userLogin);
        sb.append(", ").append(userPassword);
        sb.append(", ").append(userActive);

        sb.append(")");
        return sb.toString();
    }
}
