/*
 * This file is generated by jOOQ.
 */
package com.thhkpr.databases;


import com.thhkpr.databases.tables.Settings;
import com.thhkpr.databases.tables.Storage;
import com.thhkpr.databases.tables.Things;
import com.thhkpr.databases.tables.Users;
import com.thhkpr.databases.tables.records.SettingsRecord;
import com.thhkpr.databases.tables.records.StorageRecord;
import com.thhkpr.databases.tables.records.ThingsRecord;
import com.thhkpr.databases.tables.records.UsersRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>thhkpr</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<SettingsRecord, Integer> IDENTITY_SETTINGS = Identities0.IDENTITY_SETTINGS;
    public static final Identity<StorageRecord, Integer> IDENTITY_STORAGE = Identities0.IDENTITY_STORAGE;
    public static final Identity<ThingsRecord, Integer> IDENTITY_THINGS = Identities0.IDENTITY_THINGS;
    public static final Identity<UsersRecord, Integer> IDENTITY_USERS = Identities0.IDENTITY_USERS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<SettingsRecord> KEY_SETTINGS_PRIMARY = UniqueKeys0.KEY_SETTINGS_PRIMARY;
    public static final UniqueKey<SettingsRecord> KEY_SETTINGS_SETTINGS_ID = UniqueKeys0.KEY_SETTINGS_SETTINGS_ID;
    public static final UniqueKey<StorageRecord> KEY_STORAGE_PRIMARY = UniqueKeys0.KEY_STORAGE_PRIMARY;
    public static final UniqueKey<StorageRecord> KEY_STORAGE_STORAGE_ID = UniqueKeys0.KEY_STORAGE_STORAGE_ID;
    public static final UniqueKey<ThingsRecord> KEY_THINGS_PRIMARY = UniqueKeys0.KEY_THINGS_PRIMARY;
    public static final UniqueKey<ThingsRecord> KEY_THINGS_THING_ID = UniqueKeys0.KEY_THINGS_THING_ID;
    public static final UniqueKey<UsersRecord> KEY_USERS_PRIMARY = UniqueKeys0.KEY_USERS_PRIMARY;
    public static final UniqueKey<UsersRecord> KEY_USERS_USER_ID = UniqueKeys0.KEY_USERS_USER_ID;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ThingsRecord, StorageRecord> STORAGE_ID_FK = ForeignKeys0.STORAGE_ID_FK;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<SettingsRecord, Integer> IDENTITY_SETTINGS = Internal.createIdentity(Settings.SETTINGS, Settings.SETTINGS.SETTINGS_ID);
        public static Identity<StorageRecord, Integer> IDENTITY_STORAGE = Internal.createIdentity(Storage.STORAGE, Storage.STORAGE.STORAGE_ID);
        public static Identity<ThingsRecord, Integer> IDENTITY_THINGS = Internal.createIdentity(Things.THINGS, Things.THINGS.THING_ID);
        public static Identity<UsersRecord, Integer> IDENTITY_USERS = Internal.createIdentity(Users.USERS, Users.USERS.USER_ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<SettingsRecord> KEY_SETTINGS_PRIMARY = Internal.createUniqueKey(Settings.SETTINGS, "KEY_settings_PRIMARY", Settings.SETTINGS.SETTINGS_ID);
        public static final UniqueKey<SettingsRecord> KEY_SETTINGS_SETTINGS_ID = Internal.createUniqueKey(Settings.SETTINGS, "KEY_settings_settings_id", Settings.SETTINGS.SETTINGS_ID);
        public static final UniqueKey<StorageRecord> KEY_STORAGE_PRIMARY = Internal.createUniqueKey(Storage.STORAGE, "KEY_storage_PRIMARY", Storage.STORAGE.STORAGE_ID);
        public static final UniqueKey<StorageRecord> KEY_STORAGE_STORAGE_ID = Internal.createUniqueKey(Storage.STORAGE, "KEY_storage_storage_id", Storage.STORAGE.STORAGE_ID);
        public static final UniqueKey<ThingsRecord> KEY_THINGS_PRIMARY = Internal.createUniqueKey(Things.THINGS, "KEY_things_PRIMARY", Things.THINGS.THING_ID);
        public static final UniqueKey<ThingsRecord> KEY_THINGS_THING_ID = Internal.createUniqueKey(Things.THINGS, "KEY_things_thing_id", Things.THINGS.THING_ID);
        public static final UniqueKey<UsersRecord> KEY_USERS_PRIMARY = Internal.createUniqueKey(Users.USERS, "KEY_users_PRIMARY", Users.USERS.USER_ID);
        public static final UniqueKey<UsersRecord> KEY_USERS_USER_ID = Internal.createUniqueKey(Users.USERS, "KEY_users_user_id", Users.USERS.USER_ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<ThingsRecord, StorageRecord> STORAGE_ID_FK = Internal.createForeignKey(com.thhkpr.databases.Keys.KEY_STORAGE_PRIMARY, Things.THINGS, "storage_id_fk", Things.THINGS.STORAGE_ID);
    }
}
