/*
 * This file is generated by jOOQ.
 */
package com.thhkpr.databases.tables.records;


import com.thhkpr.databases.tables.Settings;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SettingsRecord extends UpdatableRecordImpl<SettingsRecord> implements Record3<ULong, String, String> {

    private static final long serialVersionUID = 1614324214;

    /**
     * Setter for <code>thhkpr.settings.settings_id</code>.
     */
    public void setSettingsId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>thhkpr.settings.settings_id</code>.
     */
    public ULong getSettingsId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>thhkpr.settings.settings_name</code>.
     */
    public void setSettingsName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>thhkpr.settings.settings_name</code>.
     */
    public String getSettingsName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>thhkpr.settings.settings_value</code>.
     */
    public void setSettingsValue(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>thhkpr.settings.settings_value</code>.
     */
    public String getSettingsValue() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<ULong, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<ULong, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return Settings.SETTINGS.SETTINGS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Settings.SETTINGS.SETTINGS_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Settings.SETTINGS.SETTINGS_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component1() {
        return getSettingsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getSettingsName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getSettingsValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getSettingsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSettingsName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSettingsValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SettingsRecord value1(ULong value) {
        setSettingsId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SettingsRecord value2(String value) {
        setSettingsName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SettingsRecord value3(String value) {
        setSettingsValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SettingsRecord values(ULong value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SettingsRecord
     */
    public SettingsRecord() {
        super(Settings.SETTINGS);
    }

    /**
     * Create a detached, initialised SettingsRecord
     */
    public SettingsRecord(ULong settingsId, String settingsName, String settingsValue) {
        super(Settings.SETTINGS);

        set(0, settingsId);
        set(1, settingsName);
        set(2, settingsValue);
    }
}
