/*
 * This file is generated by jOOQ.
 */
package com.thhkpr.databases.tables;


import com.thhkpr.databases.Indexes;
import com.thhkpr.databases.Keys;
import com.thhkpr.databases.Thhkpr;
import com.thhkpr.databases.tables.records.SettingsRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Settings extends TableImpl<SettingsRecord> {

    private static final long serialVersionUID = -1526666586;

    /**
     * The reference instance of <code>thhkpr.settings</code>
     */
    public static final Settings SETTINGS = new Settings();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SettingsRecord> getRecordType() {
        return SettingsRecord.class;
    }

    /**
     * The column <code>thhkpr.settings.settings_id</code>.
     */
    public final TableField<SettingsRecord, ULong> SETTINGS_ID = createField("settings_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>thhkpr.settings.settings_name</code>.
     */
    public final TableField<SettingsRecord, String> SETTINGS_NAME = createField("settings_name", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>thhkpr.settings.settings_value</code>.
     */
    public final TableField<SettingsRecord, String> SETTINGS_VALUE = createField("settings_value", org.jooq.impl.SQLDataType.VARCHAR(500), this, "");

    /**
     * Create a <code>thhkpr.settings</code> table reference
     */
    public Settings() {
        this(DSL.name("settings"), null);
    }

    /**
     * Create an aliased <code>thhkpr.settings</code> table reference
     */
    public Settings(String alias) {
        this(DSL.name(alias), SETTINGS);
    }

    /**
     * Create an aliased <code>thhkpr.settings</code> table reference
     */
    public Settings(Name alias) {
        this(alias, SETTINGS);
    }

    private Settings(Name alias, Table<SettingsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Settings(Name alias, Table<SettingsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Settings(Table<O> child, ForeignKey<O, SettingsRecord> key) {
        super(child, key, SETTINGS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Thhkpr.THHKPR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SETTINGS_PRIMARY, Indexes.SETTINGS_SETTINGS_ID, Indexes.SETTINGS_SETTINGS_SETTINGS_ID_INDEX, Indexes.SETTINGS_SETTINGS_SETTINGS_NAME_INDEX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<SettingsRecord, ULong> getIdentity() {
        return Keys.IDENTITY_SETTINGS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SettingsRecord> getPrimaryKey() {
        return Keys.KEY_SETTINGS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SettingsRecord>> getKeys() {
        return Arrays.<UniqueKey<SettingsRecord>>asList(Keys.KEY_SETTINGS_PRIMARY, Keys.KEY_SETTINGS_SETTINGS_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Settings as(String alias) {
        return new Settings(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Settings as(Name alias) {
        return new Settings(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Settings rename(String name) {
        return new Settings(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Settings rename(Name name) {
        return new Settings(name, null);
    }
}
