/*
 * This file is generated by jOOQ.
 */
package com.thhkpr.databases.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements Serializable {

    private static final long serialVersionUID = 1079754700;

    private Integer userId;
    private String  userName;
    private String  userLogin;
    private String  userPassword;
    private Integer userActive;

    public Users() {}

    public Users(Users value) {
        this.userId = value.userId;
        this.userName = value.userName;
        this.userLogin = value.userLogin;
        this.userPassword = value.userPassword;
        this.userActive = value.userActive;
    }

    public Users(
        Integer userId,
        String  userName,
        String  userLogin,
        String  userPassword,
        Integer userActive
    ) {
        this.userId = userId;
        this.userName = userName;
        this.userLogin = userLogin;
        this.userPassword = userPassword;
        this.userActive = userActive;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserLogin() {
        return this.userLogin;
    }

    public void setUserLogin(String userLogin) {
        this.userLogin = userLogin;
    }

    public String getUserPassword() {
        return this.userPassword;
    }

    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    public Integer getUserActive() {
        return this.userActive;
    }

    public void setUserActive(Integer userActive) {
        this.userActive = userActive;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(userId);
        sb.append(", ").append(userName);
        sb.append(", ").append(userLogin);
        sb.append(", ").append(userPassword);
        sb.append(", ").append(userActive);

        sb.append(")");
        return sb.toString();
    }
}
