/*
 * This file is generated by jOOQ.
 */
package com.thhkpr.db.tables.daos;


import com.thhkpr.db.tables.Settings;
import com.thhkpr.db.tables.records.SettingsRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.ULong;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class SettingsDao extends DAOImpl<SettingsRecord, com.thhkpr.db.tables.pojos.Settings, ULong> {

    /**
     * Create a new SettingsDao without any configuration
     */
    public SettingsDao() {
        super(Settings.SETTINGS, com.thhkpr.db.tables.pojos.Settings.class);
    }

    /**
     * Create a new SettingsDao with an attached configuration
     */
    @Autowired
    public SettingsDao(Configuration configuration) {
        super(Settings.SETTINGS, com.thhkpr.db.tables.pojos.Settings.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected ULong getId(com.thhkpr.db.tables.pojos.Settings object) {
        return object.getSettingsId();
    }

    /**
     * Fetch records that have <code>settings_id IN (values)</code>
     */
    public List<com.thhkpr.db.tables.pojos.Settings> fetchBySettingsId(ULong... values) {
        return fetch(Settings.SETTINGS.SETTINGS_ID, values);
    }

    /**
     * Fetch a unique record that has <code>settings_id = value</code>
     */
    public com.thhkpr.db.tables.pojos.Settings fetchOneBySettingsId(ULong value) {
        return fetchOne(Settings.SETTINGS.SETTINGS_ID, value);
    }

    /**
     * Fetch records that have <code>settings_name IN (values)</code>
     */
    public List<com.thhkpr.db.tables.pojos.Settings> fetchBySettingsName(String... values) {
        return fetch(Settings.SETTINGS.SETTINGS_NAME, values);
    }

    /**
     * Fetch records that have <code>settings_value IN (values)</code>
     */
    public List<com.thhkpr.db.tables.pojos.Settings> fetchBySettingsValue(String... values) {
        return fetch(Settings.SETTINGS.SETTINGS_VALUE, values);
    }
}
