/*
 * This file is generated by jOOQ.
 */
package com.thhkpr.databases;


import com.thhkpr.databases.tables.Settings;
import com.thhkpr.databases.tables.Storage;
import com.thhkpr.databases.tables.Things;
import com.thhkpr.databases.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in thhkpr
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>thhkpr.settings</code>.
     */
    public static final Settings SETTINGS = com.thhkpr.databases.tables.Settings.SETTINGS;

    /**
     * The table <code>thhkpr.storage</code>.
     */
    public static final Storage STORAGE = com.thhkpr.databases.tables.Storage.STORAGE;

    /**
     * The table <code>thhkpr.things</code>.
     */
    public static final Things THINGS = com.thhkpr.databases.tables.Things.THINGS;

    /**
     * The table <code>thhkpr.users</code>.
     */
    public static final Users USERS = com.thhkpr.databases.tables.Users.USERS;
}
