/*
 * This file is generated by jOOQ.
 */
package com.thhkpr.db.tables.records;


import com.thhkpr.db.tables.Things;

import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "things", schema = "thhkpr", indexes = {
    @Index(name = "PRIMARY", unique = true, columnList = "thing_id ASC"),
    @Index(name = "things_thing_id_index", columnList = "thing_id ASC"),
    @Index(name = "things_thing_name_index", columnList = "thing_name ASC"),
    @Index(name = "thing_id", unique = true, columnList = "thing_id ASC")
})
public class ThingsRecord extends UpdatableRecordImpl<ThingsRecord> implements Record7<ULong, String, String, byte[], Timestamp, Timestamp, String> {

    private static final long serialVersionUID = 904698690;

    /**
     * Setter for <code>thhkpr.things.thing_id</code>.
     */
    public void setThingId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>thhkpr.things.thing_id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "thing_id", unique = true, nullable = false, precision = 20)
    public ULong getThingId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>thhkpr.things.thing_name</code>.
     */
    public void setThingName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>thhkpr.things.thing_name</code>.
     */
    @Column(name = "thing_name", nullable = false, length = 4000)
    @NotNull
    @Size(max = 4000)
    public String getThingName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>thhkpr.things.thing_describe</code>.
     */
    public void setThingDescribe(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>thhkpr.things.thing_describe</code>.
     */
    @Column(name = "thing_describe", length = 4000)
    @Size(max = 4000)
    public String getThingDescribe() {
        return (String) get(2);
    }

    /**
     * Setter for <code>thhkpr.things.thnig_voice</code>.
     */
    public void setThnigVoice(byte... value) {
        set(3, value);
    }

    /**
     * Getter for <code>thhkpr.things.thnig_voice</code>.
     */
    @Column(name = "thnig_voice", length = 65535)
    @Size(max = 65535)
    public byte[] getThnigVoice() {
        return (byte[]) get(3);
    }

    /**
     * Setter for <code>thhkpr.things.sys_date_create</code>.
     */
    public void setSysDateCreate(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>thhkpr.things.sys_date_create</code>.
     */
    @Column(name = "sys_date_create", nullable = false)
    public Timestamp getSysDateCreate() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>thhkpr.things.sys_date_update</code>.
     */
    public void setSysDateUpdate(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>thhkpr.things.sys_date_update</code>.
     */
    @Column(name = "sys_date_update", nullable = false)
    public Timestamp getSysDateUpdate() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>thhkpr.things.sys_who_update_name</code>.
     */
    public void setSysWhoUpdateName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>thhkpr.things.sys_who_update_name</code>.
     */
    @Column(name = "sys_who_update_name", length = 500)
    @Size(max = 500)
    public String getSysWhoUpdateName() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<ULong, String, String, byte[], Timestamp, Timestamp, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<ULong, String, String, byte[], Timestamp, Timestamp, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return Things.THINGS.THING_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Things.THINGS.THING_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Things.THINGS.THING_DESCRIBE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field4() {
        return Things.THINGS.THNIG_VOICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Things.THINGS.SYS_DATE_CREATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Things.THINGS.SYS_DATE_UPDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Things.THINGS.SYS_WHO_UPDATE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component1() {
        return getThingId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getThingName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getThingDescribe();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component4() {
        return getThnigVoice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getSysDateCreate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getSysDateUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getSysWhoUpdateName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getThingId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getThingName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getThingDescribe();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value4() {
        return getThnigVoice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getSysDateCreate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getSysDateUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getSysWhoUpdateName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ThingsRecord value1(ULong value) {
        setThingId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ThingsRecord value2(String value) {
        setThingName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ThingsRecord value3(String value) {
        setThingDescribe(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ThingsRecord value4(byte... value) {
        setThnigVoice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ThingsRecord value5(Timestamp value) {
        setSysDateCreate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ThingsRecord value6(Timestamp value) {
        setSysDateUpdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ThingsRecord value7(String value) {
        setSysWhoUpdateName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ThingsRecord values(ULong value1, String value2, String value3, byte[] value4, Timestamp value5, Timestamp value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ThingsRecord
     */
    public ThingsRecord() {
        super(Things.THINGS);
    }

    /**
     * Create a detached, initialised ThingsRecord
     */
    public ThingsRecord(ULong thingId, String thingName, String thingDescribe, byte[] thnigVoice, Timestamp sysDateCreate, Timestamp sysDateUpdate, String sysWhoUpdateName) {
        super(Things.THINGS);

        set(0, thingId);
        set(1, thingName);
        set(2, thingDescribe);
        set(3, thnigVoice);
        set(4, sysDateCreate);
        set(5, sysDateUpdate);
        set(6, sysWhoUpdateName);
    }
}
