/*
 * This file is generated by jOOQ.
 */
package com.thhkpr.db.tables.records;


import com.thhkpr.db.tables.Users;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "users", schema = "thhkpr", indexes = {
    @Index(name = "PRIMARY", unique = true, columnList = "user_id ASC"),
    @Index(name = "users_user_id_index", columnList = "user_id ASC"),
    @Index(name = "users_user_name_user_login_index", columnList = "user_name ASC, user_login ASC"),
    @Index(name = "user_id", unique = true, columnList = "user_id ASC")
})
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> implements Record5<ULong, String, String, String, Integer> {

    private static final long serialVersionUID = 263881034;

    /**
     * Setter for <code>thhkpr.users.user_id</code>.
     */
    public void setUserId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>thhkpr.users.user_id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "user_id", unique = true, nullable = false, precision = 20)
    public ULong getUserId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>thhkpr.users.user_name</code>.
     */
    public void setUserName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>thhkpr.users.user_name</code>.
     */
    @Column(name = "user_name", nullable = false, length = 500)
    @NotNull
    @Size(max = 500)
    public String getUserName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>thhkpr.users.user_login</code>.
     */
    public void setUserLogin(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>thhkpr.users.user_login</code>.
     */
    @Column(name = "user_login", nullable = false, length = 80)
    @NotNull
    @Size(max = 80)
    public String getUserLogin() {
        return (String) get(2);
    }

    /**
     * Setter for <code>thhkpr.users.user_password</code>.
     */
    public void setUserPassword(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>thhkpr.users.user_password</code>.
     */
    @Column(name = "user_password", length = 80)
    @Size(max = 80)
    public String getUserPassword() {
        return (String) get(3);
    }

    /**
     * Setter for <code>thhkpr.users.user_active</code>.
     */
    public void setUserActive(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>thhkpr.users.user_active</code>.
     */
    @Column(name = "user_active", precision = 10)
    public Integer getUserActive() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<ULong, String, String, String, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<ULong, String, String, String, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return Users.USERS.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Users.USERS.USER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Users.USERS.USER_LOGIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Users.USERS.USER_PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Users.USERS.USER_ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getUserLogin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getUserPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getUserActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getUserLogin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getUserPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getUserActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value1(ULong value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value2(String value) {
        setUserName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value3(String value) {
        setUserLogin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value4(String value) {
        setUserPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value5(Integer value) {
        setUserActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord values(ULong value1, String value2, String value3, String value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(ULong userId, String userName, String userLogin, String userPassword, Integer userActive) {
        super(Users.USERS);

        set(0, userId);
        set(1, userName);
        set(2, userLogin);
        set(3, userPassword);
        set(4, userActive);
    }
}
